### ISSUE TITLE
Woo-Redact - specification and project plan

### ISSUE THREAD

**Issue by aantonop** [aantonop/woo-redact#1]
woo-redact: a data minimization and data redaction plugin for Wordpress/Woocommerce

This is inspired by the recent database breach of a cryptocurrency hardware wallet company, but applies more broadly to any e-commerce site and the need to protect PII and user privacy. 

woo-redact is a plugin that removes/blanks specific fields within the users and orders tables of WP/Woocommerce after a user's order has reached a specific order status that makes it no longer necessary to have that data about the user/order. The plugin is intended to run automatically (cron) and continuously redact user data. 

Here's the overall goal, with a user story:

A site administrator running a Woocommerce store on a hosted Wordpress without CLI, database or shell access should be able to install this plugin and: "Configure the plugin settings to automatically remove/blank the selected fields select/checkbox:[phone, address1, zip, city] from the checkbox:[Wordpress user] and checkbox:[Woocommerce orders] tables for any users with all orders as status select:[complete], within text:[N] select:[hours/days/weeks/months] of their order reaching that status"

**Comment by aantonop** [comment]
Milestones:

- [x] add a skeleton template for a Wordpress plugin with minimum functionality and hooks (cron, settings page) 
- [x] build settings page (forms, saving, loading)
- [ ] test settings page on a Wordpress/Woocommerce site
- [ ] dry run "Test now" button that shows which users/orders would be redacted but doesn't actually do it.
- [ ] "Run now" button that runs the redaction function as specified in the settings
- [ ] Cron entry that automatically runs the redaction function at the specified interval
- [ ] Release as installable plugin

**Comment by aantonop** [comment]
To create the initial scaffold/skeleton for the plugin: 
https://developer.wordpress.org/cli/commands/scaffold/plugin/

**Comment by dahifi** [comment]
I'm not a plugin dev, but I've reached out to a couple on Fiverr to see whether anyone will take it on. Most of them charge $150-300 for a custom WC plugin, I'll see if any will take it on.

**Comment by ashfame** [comment]
@aantonop All milestones are straight forward, except the data to be displayed in dry run. That can be a lot of data for some sites. Moreover, I think, just listing out Order IDs and Customer ID (name, email) would suffice in terms of letting the user review the impact, or you have more ideas on how that should look like? I have seen some plugins, just listing the count of items that will be impacted by such an action.

I will get the ball rolling on it tomorrow.

**Comment by taoteh1221** [comment]
Going to keep an eye on this repo, and get a POC together after the holiday weekend. Everything except for the 'dry run' feature is very basic work, probably 3 to 4 work days max. Not interested in grants etc, happy to do this free under GPLv3, it's a good cause / great idea.

**Comment by aantonop** [comment]
I'd rather do this thru gitcoin not fiverr

**Comment by aantonop** [comment]
> @aantonop All milestones are straight forward, except the data to be displayed in dry run. That can be a lot of data for some sites. Moreover, I think, just listing out Order IDs and Customer ID (name, email) would suffice in terms of letting the user review the impact, or you have more ideas on how that should look like? I have seen some plugins, just listing the count of items that will be impacted by such an action.
> 
> I will get the ball rolling on it tomorrow.

Yeah, I think a count of items affected would be a great way to do it, instead of showing a full list. What I want is for the admin to be able to see what the effect would be, before initiating the *actual* run.

**Comment by taoteh1221** [comment]
Well, looks like a half decent POC only took 3 to 4 hours instead of 3 to 4 days. If you guys want to try it out (untested but should work), here's my fork of the repo: https://github.com/taoteh1221/woo-redact

NOTES: 

To manually install, just put the repo files inside a new folder / directory named 'woo-redact', and upload to your 'wp-content/plugins' directory. Reload you admin plugins page, and you'll see it available to activate. 

The administration page is currently located under the WP admin 'Settings' section, titled 'Woo Redact Settings'. 

Please read the IMPORTANT-NOTES.txt and TO-DO.txt files for additional information. 

If you like what you see I can submit a pull request to your repo, and we can go from there. As mentioned previously, the 'dry run' preview logic is the most time-consuming part, so I haven't implemented it yet. I also have not implemented deleting user orders yet (only the user is deleted as of now), because...well...it's bedtime here.

Doing this for free, this is pretty straightforward stuff for me. It's my pleasure for a good cause. Holler if you have any questions.

**Comment by ashfame** [comment]
I actually found a better way to handle removal of PII leveraging what WordPress & WooCommerce already supports.

WooCommerce under its privacy settings now offers the ability to anonymize personal details, and can be set to do so automatically after a specified interval and an option to enable it on orders screen where you can select orders and manually remove personal data from them. So, its already built in.

<img width="1238" alt="Screenshot 2020-12-23 at 11 33 13 AM" src="https://user-images.githubusercontent.com/858906/102965016-fb227780-4512-11eb-9b6b-75d7adb1ddc1.png">

<img width="476" alt="Screenshot 2020-12-23 at 11 36 35 AM" src="https://user-images.githubusercontent.com/858906/102965109-2d33d980-4513-11eb-8792-a401bff2c986.png">

I tested both the cases by selecting an order and clearing personal data under it from orders screen and also letting cron clear it based on specified time duration and it works well.

-----

There is support for "Erasure requests" too where users can request export or erasure of the data (I am not sure as to where on the frontend its exposed) and admin can initiate the request for user's approval as well (they get an email) to do the same. But as long as we are ourselves purging PII this doesn't do anything else for us, other than maybe user requesting & seeing none of their personal data is stored.

---

It however doesn't touch the saved addresses under customer's account, which happens when they have placed an order or manually added their addresses. We can just attach to `woocommerce_cleanup_personal_data` hook which runs daily and that can clear out the saved address fields which are just fields in usermeta table. Best to use WordPress functions and not SQL queries directly so any caching layers are kept in loop of changes.

**Comment by ashfame** [comment]
A lower setting for `Retain inactive accounts` like 1 week or 1 day will lead to customers account being deleted altogether. So that covers the user personal data side as well, leaving a small window of time where customer data is kept. This might be acceptable as is, let me know, how else would you expect the system to do its job?

And the last bit that's of concern is the site/db backups that are kept. Old backups will continue to store data that existed before each purge operation. Ideally the backups should be encrypted with asymmetric encryption. But considering the vast number of small stores don't have the resources or that kind of setup, a proper rotational backup plan which includes purging of old backup archives is preferable.

**Comment by aantonop** [comment]
@ashfame The Woocommerce functionality does not give us fine-grained control over what is removed, at what status and what is kept. 

So, perhaps the way this plugin works is by hooking into the Woocommerce capability and providing additional settings (which fields, what status, how often) and data-redaction actions (blank specific fields in ordermeta and usermeta) to do this.

**Comment by ashfame** [comment]
@aantonop Yeah! By default it removes all PII, we can build a fine-grain control screen as described in your user-story for what data stays, though I feel like keeping any PII defeats the purpose?

Regarding at what status does this happen is clearly configurable (X days/weeks after order completion status) unless you mean something else?

**Comment by aantonop** [comment]
> Well, looks like a half decent POC only took 3 to 4 hours instead of 3 to 4 days. If you guys want to try it out (untested but should work), here's my fork of the repo: https://github.com/taoteh1221/woo-redact
> 
> NOTES:
> 
> To manually install, just put the repo files inside a new folder / directory named 'woo-redact', and upload to your 'wp-content/plugins' directory. Reload you admin plugins page, and you'll see it available to activate.
> 
> The administration page is currently located under the WP admin 'Settings' section, titled 'Woo Redact Settings'.
> 
> Please read the IMPORTANT-NOTES.txt and TO-DO.txt files for additional information.
> 
> If you like what you see I can submit a pull request to your repo, and we can go from there. As mentioned previously, the 'dry run' preview logic is the most time-consuming part, so I haven't implemented it yet. I also have not implemented deleting user orders yet (only the user is deleted as of now), because...well...it's bedtime here.
> 
> Doing this for free, this is pretty straightforward stuff for me. It's my pleasure for a good cause. Holler if you have any questions.

@taoteh1221 Really appreciate this Michael. However, we explicitly want to blank specific fields and NOT delete the user account. Woocommerce already has a facility for deleting the user account that does what you implemented. We are trying to do a more "surgical" data redaction than the Woocommerce default. See @ashfame post below

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 800.0 DAI (800.0 USD @ $1.0/DAI)  attached to it as part of the aantonop fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/aantonop/woo-redact/1/100024538).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/aantonop/woo-redact/1/100024538).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://chat.gitcoin.co/'>Gitcoin Chat</a>
* $999,238.57 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 7 months from now.
Please review their action plans below:


**1) [ashfame](https://gitcoin.co/ashfame) has been approved to start work.**

As discussed on Github, I will add screen to check/uncheck data fields for both orders and user to control what data gets redacted when WooCommerce runs the routine to erase data.
**2) [mhowerton91](https://gitcoin.co/mhowerton91) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/aantonop/woo-redact/1/100024538?mutate_worker_action=approve&worker=mhowerton91) | [reject worker](https://gitcoin.co/issue/aantonop/woo-redact/1/100024538?mutate_worker_action=reject&worker=mhowerton91))_.**

Gffhjrjdjfjxjxjjfifjfjfjckxkcnjcjcjckcmmxkmc

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/aantonop/woo-redact/1/100024538).

**Comment by aantonop** [comment]
"These users claimed they can complete the work by 265 years 11 months from now"

Oh @gitcoin, you crack me up

**Comment by taoteh1221** [comment]
@aantonop Yeah, was just a quick buildout not fully to specs before I retired for the night (not fleshed out beyond basic POC logic). No worries, just wanted to make sure somebody qualified had your back here, getting this done in a timely manner. Good luck with the project, it's a great idea! :) 

I'm going to keep working on my implementation for fun for awhile (will give you attribution for the idea, but change author to myself / remove your docs etc), so if you all run into trouble give me a holler and I'll get you back on track with what I'm working on (I've been a full stack web dev for 23 years / 8 years of weekly dev consults with customers, etc etc). 

![Screenshot from 2020-12-23 13-13-20](https://user-images.githubusercontent.com/1760489/103025908-bdc4e680-4520-11eb-8234-4e1ad1ff999a.png)

**Comment by ashfame** [comment]
@aantonop Please review #3 

Additional settings are added to WooCommerce privacy settings tab itself (screenshots are in PR).

Any order data field that one needs to retain can be unchecked and it won't be deleted by WooCommerce. Same goes for Customer, but WooCommerce doesn't routinely do anything for customers data unless manually selected under `Tools` > `Erase Personal Data` so added another option to enable such a routine which removes the selected saved address fields.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 800.0 DAI (800.0 USD @ $1.0/DAI) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/aantonop/woo-redact/1/100024538)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/aantonop/woo-redact/1/100024538).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://chat.gitcoin.co/'>Gitcoin Chat</a>
* $1,006,748.69 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by aantonop** [comment]
@ashfame How many of the milestones I listed in the second comment are done?

I can install and test this in my sandbox, maybe today or over the next few days.

**Comment by ashfame** [comment]
@aantonop Your user-story is completely covered. Please see specific comments from unchecked milestones below and let me know your thoughts:

[ ] test settings page on a Wordpress/Woocommerce site

Not needed since we are not adding our custom options page, rather utilising WooCommerce native functions to add our settings to its privacy settings page.

[ ] dry run "Test now" button that shows which users/orders would be redacted but doesn't actually do it.

Don't need this any longer since we are not skipping abstractions and updating DB directly. Both orders and customers data removal functions uses WooCommerce native functions.

[ ] "Run now" button that runs the redaction function as specified in the settings

*Orders*: Possible to select orders on orders screen and cleanup their personal data, after enabling the option in settings. Not possible to do a bulk operation, only however many you see on one page.

*Customers*: Don't have this for customers. Just the option to enable daily clearing of customer addresses.

I can add this if you think this would be useful. Handling it in long running background cron is simple irrespective of how many orders/customers one have. Thoughts?

[ ] Cron entry that automatically runs the redaction function at the specified interval

Orders are configurable (X days/weeks/months/years) but customers cleanup routine attaches itself to Woo's cleanup cron event that only runs daily by default. Need more here?

[ ] Release as installable plugin

Do you mean on official WordPress plugin repo? That would require adding a readme.txt file & then submit it for approval, which can take few days/weeks. Otherwise, this is ready as is. Downloading a zip file from Github is a valid WordPress plugin zip archive.

**Comment by aantonop** [comment]
Ok, sounds good. I will need to run some tests, this week and if it all
works I will close the issue

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__The funding of 800.0 DAI (800.00 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @ashfame.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/aantonop/woo-redact/1/100024538)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://chat.gitcoin.co/'>Gitcoin Chat</a>
* $1,166,781.71 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
